Adds options to customize notifications
stefanlogue/hydrate.nvim pull request #7
Opened 2024-03-10 15:46 UTC by mormod

This PR introduces the possibility to reword the reminder and `:HydrateNow` acknowledgement.

2024-04-05 17:56 UTC, stefanlogue requested changes

2024-04-05 17:56 UTC, stefanlogue commented on lua/hydrate/init.lua
If we are going to have custom notification messages, we need to ensure these are available for all of the notifications, as currently this does not cover the `print_minutes_until` function

2024-05-17 20:48 UTC, mormod commented on lua/hydrate/init.lua
Should be good to go now

2024-06-05 18:58 UTC, stefanlogue requested changes
Everything else looks good and I'll merge this in once this change is made, thanks again for the PR and sorry about turnaround time, been extremely busy!

2024-06-05 18:58 UTC, stefanlogue commented on CHANGELOG.md
If you can put your changes into the `Unreleased` section and remove the section you created, the release action populates this automatically then

2024-06-24 10:19 UTC, mormod commented on CHANGELOG.md
Same here, I will implement your request later this week!

2024-07-11 15:56 UTC, stefanlogue approved these changes

2024-07-11 16:00 UTC, merged

2024-07-11 16:17 UTC, stefanlogue commented
This is now available in `v0.5.0`